### PR TITLE
Edits and figure

### PR DESCRIPTION
**Pull request by skadauke**
Please take a look! I fleshed it out quite a bit. A few notes:

- I added people's affiliations as best I could find but should send around a draft of the PDF to ask people to fix them
- I don't really know bibtex well - can you add the correctly formatted reference wherever I indicated [[ref: ... ]]?
- I added Alison Hill as a co-author, because I feel her workshop was a significant piece of the conference
- As conference chair, I moved myself up to last author (keeping you as first author). I hope that's OK!

Stephan

### CODE REVIEW

**Comment by bethatkinson** [comment]
what is PBC?  I think of primary biliary cholangitis.  FYI - since I'm combining multiple comments,  I'm modifying some of what you wrote.

________________________________
From: Stephan Kadauke ***@***.***>
Sent: Wednesday, June 30, 2021 10:07 PM
To: RConsortium/r-medicine-wg ***@***.***>
Cc: Atkinson, Elizabeth J. (Beth), M.S. ***@***.***>; Review requested ***@***.***>
Subject: [EXTERNAL] [RConsortium/r-medicine-wg] Edits and figure (#4)


Please take a look! I fleshed it out quite a bit. A few notes:

  *   I added people's affiliations as best I could find but should send around a draft of the PDF to ask people to fix them
  *   I don't really know bibtex well - can you add the correctly formatted reference wherever I indicated [[ref: ... ]]?
  *   I added Alison Hill as a co-author, because I feel her workshop was a significant piece of the conference
  *   As conference chair, I moved myself up to last author (keeping you as first author). I hope that's OK!

Stephan

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/RConsortium/r-medicine-wg/pull/4

Commit Summary

  *   Edits and figure

File Changes

  *   A Rmed2020_Rjournal/Figure.png<https://github.com/RConsortium/r-medicine-wg/pull/4/files#diff-343c769f77f2f52d2b705290dc9cb603f37ddc57923b7b27da17acba4c9ad9a4> (0)
  *   M Rmed2020_Rjournal/Rmed2020_RJournal.Rmd<https://github.com/RConsortium/r-medicine-wg/pull/4/files#diff-fa55d154d8a4f70a3b49b2a9cc0242c6c0c4bbe9fe2797529a372adceb0dd5e8> (213)

Patch Links:

  *   https://github.com/RConsortium/r-medicine-wg/pull/4.patch
  *   https://github.com/RConsortium/r-medicine-wg/pull/4.diff

**Comment by MaraAlexeev** [comment]
Also, have you gotten it to knit locally to pdf? I'm having some issues and not sure yet if something is wrong with YAML or issues on my machine.

**Comment by skadauke** [comment]
Public Benefit Corporation :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bethatkinson** [comment]
yep - had to put the title in quotes and the abstract as one line instead of having separate lines.

________________________________
From: Mara Alexeev ***@***.***>
Sent: Thursday, July 1, 2021 10:42 AM
To: RConsortium/r-medicine-wg ***@***.***>
Cc: Atkinson, Elizabeth J. (Beth), M.S. ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [RConsortium/r-medicine-wg] Edits and figure (#4)


Also, have you gotten it to knit locally to pdf? I'm having some issues and not sure yet if something is wrong with YAML or issues on my machine.

**Comment by MaraAlexeev** [comment]
Great! I got everything working on my machine. As soon as you do your next merge I can take a look.

**Comment by bethatkinson** [comment]
I've check in the next version but now I'm trying to fix the yaml header again

________________________________
From: Mara Alexeev ***@***.***>
Sent: Thursday, July 1, 2021 11:55 AM
To: RConsortium/r-medicine-wg ***@***.***>
Cc: Atkinson, Elizabeth J. (Beth), M.S. ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [RConsortium/r-medicine-wg] Edits and figure (#4)


Great! I got everything working on my machine. As soon as you do your next merge I can take a look.

**Comment by MaraAlexeev** [comment]
Questions: 
- Where is figure 1?
- This sentence is unclear: Because there were more people interested than slots available, so we randomly selected from all who were interested and the rest listed after the course was finished.  
- I recommend changing COVID (or versions) to COVID-19 for consistency

**Comment by bethatkinson** [comment]
great catches - I'll fix.

________________________________
From: Mara Alexeev ***@***.***>
Sent: Thursday, July 1, 2021 3:42 PM
To: RConsortium/r-medicine-wg ***@***.***>
Cc: Atkinson, Elizabeth J. (Beth), M.S. ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [RConsortium/r-medicine-wg] Edits and figure (#4)


Questions:

  *   Where is figure 1?
  *   This sentence is unclear: Because there were more people interested than slots available, so we randomly selected from all who were interested and the rest listed after the course was finished.
  *   I recommend changing COVID (or versions) to COVID-19 for consistency

**Pull request merged**
